services:
  minio:
    image: minio/minio
    container_name: databend-storage
    environment:
      MINIO_ROOT_USER: $MINIO_ROOT_USER
      MINIO_ROOT_PASSWORD: $MINIO_ROOT_PASSWORD
    networks:
      - databend-network
    ports:
      - 9000:9000
      - 9001:9001
    command: ["server", "/data", "--console-address", ":9001"]

  storage-setup:
    image: minio/mc
    depends_on:
      - minio
    networks:
      - databend-network
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 $MINIO_ROOT_USER $MINIO_ROOT_PASSWORD;
      /usr/bin/mc mb myminio/$MINIO_BUCKET;
      /usr/bin/mc cp -r /source-data myminio/$MINIO_BUCKET;
      exit 0;
      "
    volumes:
      - ./source-data:/source-data

  databend:
    depends_on: 
      storage-setup:
        condition: service_completed_successfully
    image: datafuselabs/databend
    container_name: databend-platform
    environment:
      QUERY_DEFAULT_USER: $DATABEND_USER
      QUERY_DEFAULT_PASSWORD: $DATABEND_PASSWORD
      QUERY_STORAGE_TYPE: s3
      AWS_S3_ENDPOINT: http://minio:9000
      AWS_S3_BUCKET: $MINIO_BUCKET
      AWS_ACCESS_KEY_ID: $MINIO_ROOT_USER
      AWS_SECRET_ACCESS_KEY: $MINIO_ROOT_PASSWORD
    networks:
      - databend-network
    ports:
      - 3307:3307
      - 8000:8000
      - 8124:8124
      - 8900:8900
      - 8080:8080

networks:
  databend-network:
